name: Sprawdzanie dostępności

on:
  schedule:
    - cron: "0 7 * * *"  # raz dziennie o 7:00 UTC (9:00 w Polsce)
  workflow_dispatch:

jobs:
  check_product:
    runs-on: ubuntu-latest
    steps:
      - name: Klon repo
        uses: actions/checkout@v3

      - name: Instalacja bibliotek
        run: pip install beautifulsoup4 requests

      - name: Start
        run: python check_product.py
